language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "node"
install: 
  - cd treehouse-js-web-scraper
  - npm install 
script: 
  - npm test
after_success:
  - coveralls