language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "node"
install: 
  - cd treehouse-js-web-scraper
  - npm install 
script: 
  - npm run test-travis
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"